# Generated by Django 3.1.7 on 2021-02-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_remove_prodstock_unique_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodstock',
            name='unique_number',
            field=models.PositiveIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
